services:
  firebase-emulator:
    build: ./firebase
    ports:
      - "${FIREBASE_UI_PORT:-4000}:4000"
      - "${FIREBASE_AUTH_PORT:-9099}:9099"
      - "${FIREBASE_FIRESTORE_PORT:-8080}:8080"
      - "${FIREBASE_FUNCTIONS_PORT:-5001}:5001"
    volumes:
      - ./firebase:/workspace
